### ISSUE TITLE
Portenta H7 bootloader build issue

### ISSUE THREAD

**Issue by beriberikix** [arduino/ArduinoCore-zephyr#10]
**Describe the bug**

When compiling a blank example, I see "Bootloader file specified but missing" from the compile output. Subsequently while flashing does complete, when I use any example it doesn't actually work (ex. Blink.) I'm guessing it's related to this issue.

**Target board + cli verbose compilation output**

FQBN: arduino:zephyr:portentah7
Using board 'portentah7' from platform in folder: /Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0
Using core 'arduino' from platform in folder: /Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0

Detecting libraries used...
/Users/jberi/Library/Arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-g++ -g -Os -c -w -DLL_EXTENSION_BUILD -DCONFIG_ARDUINO_API_SERIAL_BUFFER_SIZE=256 -DHSE_VALUE=25000000 -DKERNEL -DK_HEAP_MEM_POOL_SIZE=16384 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -DSTM32H747xx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -imacros/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h -imacros/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -fdata-sections -ffunction-sections -fno-unwind-tables -fno-strict-aliasing -fno-printf-return-value -fno-common -mcpu=cortex-m7 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop --specs=picolibc.specs -D_POSIX_THREADS -mlong-calls -nodefaultlibs -DCORE_CM7 -mcpu=cortex-m7 -mfloat-abi=softfp -mfpu=fpv5-d16 -w -x c++ -E -CC -DARDUINO=10607 -DARDUINO_PORTENTA_H7 -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=1 -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7 -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino/api/deprecated -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino/api/deprecated-avr-comp -iprefix/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7 @/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/includes.txt /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch/sketch_dec10a.ino.cpp -o /dev/null
Generating function prototypes...
/Users/jberi/Library/Arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-g++ -g -Os -c -w -DLL_EXTENSION_BUILD -DCONFIG_ARDUINO_API_SERIAL_BUFFER_SIZE=256 -DHSE_VALUE=25000000 -DKERNEL -DK_HEAP_MEM_POOL_SIZE=16384 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -DSTM32H747xx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -imacros/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h -imacros/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -fdata-sections -ffunction-sections -fno-unwind-tables -fno-strict-aliasing -fno-printf-return-value -fno-common -mcpu=cortex-m7 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop --specs=picolibc.specs -D_POSIX_THREADS -mlong-calls -nodefaultlibs -DCORE_CM7 -mcpu=cortex-m7 -mfloat-abi=softfp -mfpu=fpv5-d16 -w -x c++ -E -CC -DARDUINO=10607 -DARDUINO_PORTENTA_H7 -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=1 -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7 -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino/api/deprecated -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino/api/deprecated-avr-comp -iprefix/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7 @/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/includes.txt /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch/sketch_dec10a.ino.cpp -o /private/var/folders/5t/0nkk7c013x51lbsn7389mstw0000gn/T/596048874/sketch_merged.cpp
/Users/jberi/Library/Arduino15/packages/builtin/tools/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /private/var/folders/5t/0nkk7c013x51lbsn7389mstw0000gn/T/596048874/sketch_merged.cpp
Compiling sketch...
/Users/jberi/Library/Arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-g++ -g -Os -c -w -DLL_EXTENSION_BUILD -DCONFIG_ARDUINO_API_SERIAL_BUFFER_SIZE=256 -DHSE_VALUE=25000000 -DKERNEL -DK_HEAP_MEM_POOL_SIZE=16384 -DPICOLIBC_LONG_LONG_PRINTF_SCANF -DSTM32H747xx -DUSE_FULL_LL_DRIVER -DUSE_HAL_DRIVER -D__LINUX_ERRNO_EXTENSIONS__ -D__PROGRAM_START -D__ZEPHYR__=1 -imacros/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/llext-edk/include/zephyr/include/generated/zephyr/autoconf.h -imacros/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/llext-edk/include/zephyr/include/zephyr/toolchain/zephyr_stdint.h -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -fdata-sections -ffunction-sections -fno-unwind-tables -fno-strict-aliasing -fno-printf-return-value -fno-common -mcpu=cortex-m7 -mthumb -mabi=aapcs -mfp16-format=ieee -mtp=soft -Wall -Wformat -Wformat-security -Wno-format-zero-length -Wdouble-promotion -Wpointer-arith -Wexpansion-to-defined -Wno-unused-but-set-variable -fno-asynchronous-unwind-tables -ftls-model=local-exec -fno-reorder-functions --param=min-pagesize=0 -fno-defer-pop --specs=picolibc.specs -D_POSIX_THREADS -mlong-calls -nodefaultlibs -DCORE_CM7 -MMD -mcpu=cortex-m7 -mfloat-abi=softfp -mfpu=fpv5-d16 -DARDUINO=10607 -DARDUINO_PORTENTA_H7 -DARDUINO_ARCH_ZEPHYR -DARDUINO_ARCH_ZEPHYR -DARDUINO_LIBRARY_DISCOVERY_PHASE=0 -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7 -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino/api/deprecated -I/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/cores/arduino/api/deprecated-avr-comp -iprefix/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7 @/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/arduino_portenta_h7/includes.txt /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch/sketch_dec10a.ino.cpp -o /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch/sketch_dec10a.ino.cpp.o
Compiling libraries...
Compiling core...
Using previously compiled file: /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/core/variant.cpp.o
Using precompiled core: /Users/jberi/Library/Caches/arduino/cores/arduino_zephyr_portentah7_debug_false_dcd9843df91bf477df4fb341872b1718/core.a
Linking everything together...
/Users/jberi/Library/Arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-g++ -L/Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2 -r -Wl,--gc-sections -e main -fno-exceptions -fno-rtti -fno-threadsafe-statics -fno-unwind-tables -fno-use-cxa-atexit -T/Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/variants/llext/linker_script.ld -Wl,-Map,/Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.map --specs=nosys.specs -o /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.elf /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch/sketch_dec10a.ino.cpp.o /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/core/variant.cpp.o /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/../../cores/arduino_zephyr_portentah7_debug_false_dcd9843df91bf477df4fb341872b1718/core.a -lstdc++ -lsupc++ -lnosys -nostdlib
/Users/jberi/Library/Arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-objcopy -O binary /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.elf /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.bin
Bootloader file specified but missing: /Users/jberi/Library/Arduino15/packages/arduino/hardware/zephyr/0.1.0/bootloaders/zephyr-arduino_portenta_h7.bin
/Users/jberi/Library/Arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-objcopy -O ihex -R .eeprom /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.elf /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.hex
/Users/jberi/Library/Arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-strip --strip-debug /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.elf -o/Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.llext
/Users/jberi/Library/Arduino15/packages/arduino/tools/zephyr-post-build-tool/0.0.2/post_build /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.llext
File copied and saved as /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.llext.dfu

/Users/jberi/Library/Arduino15/packages/zephyr/tools/arm-zephyr-eabi/0.16.8/bin/arm-zephyr-eabi-size -A /Users/jberi/Library/Caches/arduino/sketches/B85EE534717219A0C2A559AD3C1520A2/sketch_dec10a.ino.elf
Sketch uses 1474 bytes (0%) of program storage space. Maximum is 786432 bytes.
Global variables use 2652 bytes (0%) of dynamic memory, leaving 520972 bytes for local variables. Maximum is 523624 bytes.

**Mandatory: attach the sketch**

```
void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

**Additional context**

I'm on a Apple M2 running Sequoia 15.1.1, Arduino IDE 2.3.4 & CLI 1.1.1.

**Comment by facchinm** [comment]
Hi @beriberikix ,
the "missing bootloader" warning is only a warning and should not compromise the functionality. After flashing the loader for the first time, the first sketch should be loaded in the same way (by ending the board forcefully in bootloader mode via a double tap on the reset button); may it be the case?
