### ISSUE TITLE
Fail to burn bootloader: bossac not found

### ISSUE THREAD

**Issue by gsurrel** [arduino/ArduinoCore-zephyr#9]
**Describe the bug**
I tried to follow the "First set-up" for Zephyr with the Nano 33 BLE Sense board:
- Install the Arduino 2+ IDE (Version: 2.3.4, 2024-12-03T10:51:12.539Z)
- Install the board support package for Zephyr boards
- Set the board to flash the bootloader
- Select the board/port/programmer
- Choose "Burn bootloader"

**Target board + cli verbose compilation output**
Here is the error that happens:

```
"{runtime.tools.bossac-1.9.1-arduino2.path}/bossac" -d --port=ttyACM0 -U -i -e -w "/home/gsurrel/.arduino15/packages/arduino/hardware/zephyr/0.1.0/firmwares/zephyr-arduino_nano_33_ble_sense.bin" --offset 0x0000 -R
Failed to burn bootloader: cannot execute upload tool: fork/exec {runtime.tools.bossac-1.9.1-arduino2.path}/bossac: no such file or directory
```

**Additional context**
I have the impression some tools are missing:

```sh
$ ls $HOME/.arduino15/packages/arduino/tools/
arduinoOTA  avrdude  avr-gcc  dfu-util  zephyr-post-build-tool
```

**Comment by facchinm** [comment]
Good catch! We missed some tools due to the fact that, if you already have the mbed_nano core installed, tools are already there 😅 
Amending the json right now; if you want to bypass the issue, just install `mbed_nano` core from package manager in the meantime 😉
